---
# https://kubernetes.io/docs/setup/independent/install-kubeadm/

- name: Set up kubernetes stable repository
  yum_repository:
    name: kubernetes
    file: kubernetes
    description: Kubernetes Official Stable Repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    #exclude: kube*
    state: present

- name: Set SELinux in permissive mode (1/2)
  command: setenforce 0
  when:
    - ansible_selinux.status == 'enabled'
    - run_init | bool

- name: Set SELinux in permissive mode (2/2)
  selinux:
    state: disabled

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Configure net bridge filter (1/2)
  template:
    src: k8s.conf.j2
    dest: "/etc/sysctl.d/k8s.conf"

- name: Configure net bridge filter (2/2)
  command: sysctl --system
  when: run_init | bool

- name: Install kubeadm kubelet and kubectl
  yum:
    name:
      - kubelet-{{ k8s_version }}
      - kubeadm-{{ k8s_version }}
      - kubectl-{{ k8s_version }}
    disable_excludes: kubernetes
    update_cache: yes
    state: present

- name: Start kubelet service
  systemd:
    daemon-reload: yes
    name: kubelet
    enabled: yes
    state: started
