---
# tasks file for proxy

- name: Install EPEL
  yum:
    name:
      - epel-release
    update_cache: yes
    state: present

- name: Install Certbot
  yum:
    name:
      - certbot
    update_cache: yes
    state: present

- name: Install HAProxy
  yum:
    name:
      - haproxy
    update_cache: yes
    state: present

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  when: run_init | bool

- name: Start HAProxy
  systemd:
    name: haproxy
    enabled: yes
    state: started
