- hosts: docker-nodes
  gather_facts: true

  vars:
    docker_ver: "18.03.1~ce-0~ubuntu"

  tasks:
    - import_tasks: tasks/set-timezone.yaml

    - import_tasks: tasks/disable-firewall.yaml

    - import_tasks: tasks/set-hostname.yaml

    - import_tasks: tasks/docker.yaml

#    - name: Stop docker daemon
#      systemd:
#        name: docker
#        state: stopped
#
#    - name: stat docker
#      stat: path=/mnt/docker
#      register: need_move
#
#    - name: Move docker base to mnt
#      command: mv -v /var/lib/docker /mnt
#      when: not need_move.stat.exists
#
#    - name: Create symbolic link
#      file:
#        src: /mnt/docker
#        dest: /var/lib/docker
#        state: link
#      when: not need_move.stat.exists
#
#    - name: Start docker daemon
#      systemd:
#        name: docker
#        state: started
