- hosts: kube-nodes
  gather_facts: False

  tasks:
    - import_tasks: tasks/ubuntu-minimal-python.yaml

    - import_tasks: tasks/curl-apt-over-https.yaml

    - import_tasks: tasks/set-timezone.yaml

    - import_tasks: tasks/disable-firewall.yaml

    - import_tasks: tasks/set-hostname.yaml

#    - import_tasks: tasks/set-hosts.yaml

    - import_tasks: tasks/docker.yaml

#    - name: Stop docker daemon
#      systemd:
#        name: docker
#        state: stopped
#
#    - name: stat docker
#      stat: path=/mnt/docker
#      register: need_move
#
#    - name: Move docker base to mnt
#      command: mv -v /var/lib/docker /mnt
#      when: not need_move.stat.exists
#
#    - name: Create symbolic link
#      file:
#        src: /mnt/docker
#        dest: /var/lib/docker
#        state: link
#      when: not need_move.stat.exists
#
#    - name: Start docker daemon
#      systemd:
#        name: docker
#        state: started

    - name: Add Kubernetes official GPG key
#      shell: "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -"
      apt_key:
        id: BA07F4FB
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Set up the Docker stable repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Installing kubeadm kubelet and kubectl
      apt:
        name:
          - kubelet=1.10.2-00
          - kubeadm=1.10.2-00
          - kubectl=1.10.2-00
        install_recommends: no
        update_cache: yes
        allow_unauthenticated: yes

#    Check Docker Cgroup driver: docker info | grep -i cgroup
#    Adjust the Kubelet Cgroup driver if different to Docker Cgroup driver
#
#    https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
#    --cgroup-driver string     Default: "cgroupfs"
#     Driver that the kubelet uses to manipulate cgroups on the host. Possible values: 'cgroupfs', 'systemd'
#
#    As of v1.10, the default is already cgroupfs, so this is no longer required.
#
#    - name: Adjust cgroup-driver flag
#      shell: "sed -i 's/cgroup-driver=systemd/cgroup-driver=cgroupfs/g' /etc/systemd/system/kubelet.service.d/10-kubeadm.conf"

    - name: Enable and restart kubelet
      systemd:
        daemon-reload: yes
        name: kubelet
        enabled: yes
        state: restarted
