- hosts: kube-nodes
  gather_facts: False

  tasks:
    - import_tasks: tasks/ubuntu-minimal-python.yaml

    - import_tasks: tasks/set-timezone.yaml
      vars:
        tz: Australia/Melbourne

    - import_tasks: tasks/set-hostname.yaml

    - import_tasks: tasks/set-hosts.yaml

    - import_tasks: tasks/disable-firewall.yaml

    - import_tasks: tasks/curl-apt-over-https.yaml

    - import_tasks: tasks/docker.yaml
      vars:
        docker_ver: 18.03.0~ce-0~ubuntu

#    - name: Stop docker daemon
#      systemd:
#        name: docker
#        state: stopped
#
#    - name: stat docker
#      stat: path=/mnt/docker
#      register: need_move
#
#    - name: Move docker base to mnt
#      command: mv -v /var/lib/docker /mnt
#      when: not need_move.stat.exists
#
#    - name: Create symbolic link
#      file:
#        src: /mnt/docker
#        dest: /var/lib/docker
#        state: link
#      when: not need_move.stat.exists
#
#    - name: Start docker daemon
#      systemd:
#        name: docker
#        state: started

    - name: Add Kubernetes official GPG key
      shell: "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -"

    - name: Set up the Docker stable repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Installing kubeadm kubelet and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        install_recommends: no
        update_cache: yes
        allow_unauthenticated: yes

    - name: Adjust cgroup-driver flag
      shell: "sed -i 's/cgroup-driver=systemd/cgroup-driver=cgroupfs/g' /etc/systemd/system/kubelet.service.d/10-kubeadm.conf"

    - name: Enable and restart kubelet
      systemd:
        daemon-reload: yes
        name: kubelet
        enabled: yes
        state: restarted

