- hosts: proxy-servers
  gather_facts: true

  tasks:

    - import_tasks: tasks/certbot.yaml

    - name: Install haproxy
      apt:
        name:
          - haproxy
        state: latest
        install_recommends: no

    - name: Enable and Start haproxy
      systemd:
        name: haproxy.service
        enabled: yes
        state: restarted
